server:
  port: 8090
  tomcat:
    mbeanregistry:
      enabled: true
    max-connections: 200
    threads:
      max: 150        # 设定处理客户请求的线程的最大数目，决定了服务器可以同时响应客户请求的数,默认200
      min-spare: 50   # 初始化线程数,最小空闲线程数,默认是10
    accept-count: 10  # 等待队列长度

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

spring:
  datasource:
    username: root
    password: lain_007
    url: jdbc:mysql://110.41.180.185:3306/group_buying_platform?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库配置；启动时配置数据库资源信息
  rabbitmq:
    addresses: 47.108.69.78
    port: 5672
    username: lain
    password: lain_007
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个
    template:
      delivery-mode: persistent # 确保全局默认设置为持久化（可选）
    # 消息配置
    config:
      # 生产者
      producer:
        # 绑定交换机，统一一套交换机
        exchange: group_buy_market_exchange
        # 消息主题配置；路由key、队列
        topic_team_success:
          # 消息主题
          routing_key: topic.team_success
          # 消费队列
          queue: group_buy_market_queue_2_topic_team_success
# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy
# Redis
redis:
  sdk:
    config:
      host: localhost
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
      password: _rem000
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
    #    日志
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

dubbo:
  application:
    name: group-buying-platform  # 应用名称
    version: 1.0  # 应用版本
  registry:
    id: nacos-registry  # 注册中心ID 单注册中心不需要配置 多个注册中心需要id作为唯一标识
    address: nacos://110.41.180.185:8848   #Nacos注册中心地址
  protocol:
    name: dubbo  # 使用Dubbo协议
    port: -1  # 自动选择端口
  scan:
    base-packages: top.javarem.api  # 扫描指定的包

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml